"""Initial migration

Revision ID: fedc9fbd8de5
Revises: 
Create Date: 2023-04-30 14:53:38.851865

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'fedc9fbd8de5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE jhas SET SCHEMA {SCHEMA};")

    op.create_table('ppes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('jha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jha_id'], ['jhas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE ppes SET SCHEMA {SCHEMA};")

    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('jha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jha_id'], ['jhas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE steps SET SCHEMA {SCHEMA};")

    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('jha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jha_id'], ['jhas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE trainings SET SCHEMA {SCHEMA};")

    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE controls SET SCHEMA {SCHEMA};")

    op.create_table('hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('consequence', sa.String(length=300), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE hazards SET SCHEMA {SCHEMA};")
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hazards')
    op.drop_table('controls')
    op.drop_table('trainings')
    op.drop_table('steps')
    op.drop_table('ppes')
    op.drop_table('jhas')
    # ### end Alembic commands ###
